defaults:
  - model
  - data
  - project
  - _self_
track_in_clearml: true
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-4
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 5
trainer_conf:
  max_epochs: 60
  check_val_every_n_epoch: 5
  log_every_n_steps: 10
  precision: 32-true
  gradient_clip_val: null
  accumulate_grad_batches: 1
  deterministic: false
  fast_dev_run: false
  accelerator: auto
  enable_checkpointing: true
module_conf:
  interval: epoch
  frequency: ${trainer_conf.check_val_every_n_epoch}
  monitor: val_loss_epoch
  include_background: false
  batches_to_visualize: 5
model_ckpt_conf:
  monitor: val_loss_epoch
  save_on_exception: true
  mode: min
  save_top_k: 1
  filename: best-{epoch:02d}-{${model_ckpt_conf.monitor}:.2f}
